### ISSUE TITLE
The colab is no longer working

### ISSUE THREAD

**Issue by zabinzsur** [camenduru/tortoise-tts-colab#1]
There are some warnings about numpy not building, and then the colab seems to work, and a gradio link shows up. But when we try to generatic voices, it just disconnects.

Here is a new/improved versoin of tortoise-tts with GUI
https://git.ecker.tech/mrq/ai-voice-cloning

Can you base your colab on that? For example:
https://git.ecker.tech/mrq/ai-voice-cloning/src/branch/master/notebook_colab.ipynb
Is a working colab.

**Comment by camenduru** [comment]
Hi @zabinzsur 👋 thanks for the suggestion ❤ please test
